# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Nico/Documents/Projects/Firmware/FPGA_Bomberman/FPGA_Bomberman.srcs/sources_1/ip/pillar_dm/pillar_dm.xci
# IP: The module: 'pillar_dm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Nico/Documents/Projects/Firmware/FPGA_Bomberman/FPGA_Bomberman.gen/sources_1/ip/pillar_dm/pillar_dm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pillar_dm'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Nico/Documents/Projects/Firmware/FPGA_Bomberman/FPGA_Bomberman.srcs/sources_1/ip/pillar_dm/pillar_dm.xci
# IP: The module: 'pillar_dm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Nico/Documents/Projects/Firmware/FPGA_Bomberman/FPGA_Bomberman.gen/sources_1/ip/pillar_dm/pillar_dm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pillar_dm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
